### ISSUE TITLE
False positive warnings in SPIR-V validation

### ISSUE THREAD

**Issue by jkunstwald** [project-arcana/phantasm-hardware-interface#5]
HLSL shaders with if-conditions inside of loop bodies produce false positive SPIR-V validation warnings in Vulkan if validation is enabled. This is either a bug in the validation layers, or in DXC, but has no observable effect beyond the warnings.
See microsoft/DirectXShaderCompiler#2643

**Comment by ehsannas** [comment]
I think this issue is a duplicate of https://github.com/KhronosGroup/SPIRV-Tools/issues/3260

**Comment by ehsannas** [comment]
As I explained in https://github.com/microsoft/DirectXShaderCompiler/issues/2643, you might be hitting this issue because your DXC version hadn't picked up the fix from SPIRV-Tools. Please use the latest DXC and let us know if you still face the issue. Thanks.

**Comment by jkunstwald** [comment]
Yes, thank you, current DXC fixes this issue.
